version: "2"
services:
  db:
    image: mysql:5.7
    volumes:
      - "./db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: rockrblog
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
  web:
    volumes:
      - ./:/backend/
    depends_on:
      - db
    image: webdevops/php-apache
    links:
      - db
    ports:
      - "81:80"
    restart: always
    environment:
      WEB_DOCUMENT_ROOT: /backend/backend/public